sudo: required
services:
  - docker

dist: trusty

env:
  - SHA=$(git rev-parse --short=7 HEAD)

before_install:
  - |
    docker image build \
      --tag juliocesarmidia/app-rabbit:$SHA \
      ./python-rabbitmq/rabbit/

script:
  - |
    docker container run -it --rm \
      --entrypoint "" \
      juliocesarmidia/app-rabbit:$SHA \
      hostname

after_success:
  - |
    docker image build \
      --tag juliocesarmidia/app-rabbit:$SHA \
      --tag juliocesarmidia/app-rabbit:latest \
      ./python-rabbitmq/rabbit/

    docker image build \
      --tag juliocesarmidia/app-consumer:$SHA \
      --tag juliocesarmidia/app-consumer:latest \
      ./python-rabbitmq/consumer/

    docker image build \
      --tag juliocesarmidia/app-publisher:$SHA \
      --tag juliocesarmidia/app-publisher:latest \
      ./python-rabbitmq/publisher/

    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    docker image push juliocesarmidia/app-rabbit:latest
    docker image push juliocesarmidia/app-rabbit:$SHA

    docker image push juliocesarmidia/app-consumer:latest
    docker image push juliocesarmidia/app-consumer:$SHA

    docker image push juliocesarmidia/app-publisher:latest
    docker image push juliocesarmidia/app-publisher:$SHA
