sudo: required
services:
  - docker

dist: trusty

env:
  - SHA=$(git rev-parse HEAD)

before_install:
  - docker image build --tag juliocesarmidia/app-rabbit:$SHA -f ./Dockerfile .

script:
  - docker container run -it --rm --name edent-app --entrypoint "" juliocesarmidia/app-rabbit:$SHA bash -c "echo OK && exit 0"

after_success:
  - docker image build --tag juliocesarmidia/app-rabbit:$SHA --tag juliocesarmidia/app-rabbit:v1.0.0 -f ./rabbitmq/Dockerfile ./rabbitmq/
  - docker image build --tag juliocesarmidia/app-consumer:$SHA --tag juliocesarmidia/app-consumer:v1.0.0 -f ./consumer-app/Dockerfile ./consumer-app/
  - docker image build --tag juliocesarmidia/app-publisher:$SHA --tag juliocesarmidia/app-publisher:v1.0.0 -f ./publisher-app/Dockerfile ./publisher-app/

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker image push juliocesarmidia/app-rabbit:v1.0.0
  - docker image push juliocesarmidia/app-rabbit:$SHA

  - docker image push juliocesarmidia/app-consumer:v1.0.0
  - docker image push juliocesarmidia/app-consumer:$SHA

  - docker image push juliocesarmidia/app-publisher:v1.0.0
  - docker image push juliocesarmidia/app-publisher:$SHA

# docker image build -t juliocesarmidia/app-rabbit:v1.0.0 -f ./rabbitmq/Dockerfile ./rabbitmq/
# docker image push juliocesarmidia/app-rabbit:v1.0.0
