apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbit-statefulset
  namespace: default
  labels:
    app: apprabbit

spec:
  replicas: 1
  revisionHistoryLimit: 100

  serviceName: rabbit-service

  selector:
    matchLabels:
      app: apprabbit

  template:
    metadata:
      name: app-rabbit
      labels:
        app: apprabbit

    spec:
      containers:
        - name: rabbit
          image: juliocesarmidia/app-rabbit:latest

          ports:
            - containerPort: 5672
              name: rabbit-port

          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"

            limits:
              memory: "256Mi"
              cpu: "400m"

      restartPolicy: Always
