apiVersion: apps/v1
kind: Deployment
metadata:
  name: deadletter
  namespace: default
  labels:
    app: deadletter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deadletter
  template:
    metadata:
      name: deadletter
      labels:
        app: deadletter
    spec:
      containers:
        - name: deadletter
          image: juliocesarmidia/app-deadletter:v1.0.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "while true; do sleep 5; echo WAITING $RABBIT_HOST && nc -z $RABBIT_HOST 5672 1> /dev/null 2>&1; test $? == 0 && echo HEALTH && break; done; echo CALLING SCRIPT && python -u main.py"]
          env:
            - name: RABBIT_HOST
              value: rabbit-service
            - name: RABBIT_PORT
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: RABBIT_PORT
            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: RABBIT_USER
            - name: RABBIT_PASS
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: RABBIT_PASS
            - name: RABBIT_QUEUE
              value: dead_letter
          resources:
            requests:
              memory: "128Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "300m"
      restartPolicy: Always
