apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-deployment
  namespace: default
  labels:
    app: apprabbit

spec:
  # replicas: 3
  revisionHistoryLimit: 100

  selector:
    matchLabels:
      app: apprabbit

  strategy:
    type: Recreate

  template:
    metadata:
      name: app-publisher
      labels:
        app: apprabbit

    spec:
      containers:
        - name: client
          image: juliocesarmidia/app-publisher:v1.0.0

          command: ["/bin/sh"]
          args: ["-c", "while true; do sleep 15; echo WAITING FOR RABBIT :: $RABBIT_HOST && nc -z $RABBIT_HOST 5672 1> /dev/null 2>&1; test $? == 0 && echo RABBIT HEALTH && break; done; echo CALLING SCRIPT && /usr/local/bin/python /app/publisher.py"]

          ports:
            - containerPort: 80
              name: publisher-port

          env:
            - name: RABBIT_HOST
              value: rabbit-service

            - name: RABBIT_PORT
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: RABBIT_PORT

            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: RABBIT_USER

            - name: RABBIT_PASS
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: RABBIT_PASS

            - name: RABBIT_QUEUE
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: RABBIT_QUEUE

            - name: RABBIT_ROUTING_KEY
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: RABBIT_ROUTING_KEY

          resources:
            requests:
              memory: "128Mi"
              cpu: "150m"

            limits:
              memory: "256Mi"
              cpu: "300m"

      restartPolicy: Always
