apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbit-statefulset
  namespace: default
  labels:
    app: rabbit
spec:
  replicas: 1
  serviceName: rabbit-service
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      name: app-rabbit
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbit
          image: juliocesarmidia/app-rabbit:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
              name: rabbit-port
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
  namespace: default
  labels:
    app: rabbit
spec:
  type: ClusterIP
  selector:
    app: rabbit
  ports:
    - protocol: TCP
      port: 5672
      targetPort: rabbit-port
