apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
  namespace: default
  labels:
    app: apprabbit

spec:
  type: ClusterIP

  selector:
    app: apprabbit

  ports:
    - protocol: TCP
      port: 5672
      targetPort: rabbit-port
