apiVersion: v1
kind: Secret
metadata:
  name: env-secrets
  namespace: default
type: Opaque
data:
  RABBIT_PORT: NTY3Mg==
  RABBIT_USER: ZGV2
  RABBIT_PASS: ZGV2

# kubectl get secret env-secrets
# kubectl describe secret env-secrets

# kubectl create secret generic env-secrets \
#   --from-literal=RABBIT_PORT=5672 \
#   --from-literal=RABBIT_USER=dev \
#   --from-literal=RABBIT_PASS=dev
